apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: ghcr.io/cage1016/add-cloud-run
      buildpacks:
        builder: "gcr.io/buildpacks/builder:v1"
        dependencies:
          paths:
            - cmd/add/main.go
            - internal/**
        env:
          - GOOGLE_BUILDABLE=cmd/add/main.go
  tagPolicy:
    sha256: {}
  local:
    push: true